### ISSUE TITLE
Can't initialize the site

### ISSUE THREAD

**Issue by rm2k** [Anomareh/mynt#71]
The mynt installed without any complaints on windows machine.

But as soon as i run `mynt --version`, I'm greeted with the following error message:

`Traceback (most recent call last):
  File "c:\python34\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Envs\myntenv\Scripts\mynt.exe\__main__.py", line 5, in <module>
  File "c:\users\username\envs\myntenv\lib\site-packages\mynt\main.py", line 7, in <module>
    from mynt.core import Mynt
  File "c:\users\username\envs\myntenv\lib\site-packages\mynt\core.py", line 22, in <module>
    from mynt.server import RequestHandler, Server
  File "c:\users\username\envs\myntenv\lib\site-packages\mynt\server.py", line 5, in <module>
    from SimpleHTTPServer import SimpleHTTPRequestHandler
ImportError: No module named 'SimpleHTTPServer'`

Again, running `mynt init mysite`, I seem to get the same message:

`Traceback (most recent call last):
  File "c:\python34\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Envs\myntenv\Scripts\mynt.exe\__main__.py", line 5, in <module>
  File "c:\users\username\envs\myntenv\lib\site-packages\mynt\main.py", line 7, in <module>
    from mynt.core import Mynt
  File "c:\users\username\envs\myntenv\lib\site-packages\mynt\core.py", line 22, in <module>
    from mynt.server import RequestHandler, Server
  File "c:\users\username\envs\myntenv\lib\site-packages\mynt\server.py", line 5, in <module>
    from SimpleHTTPServer import SimpleHTTPRequestHandler
ImportError: No module named 'SimpleHTTPServer'`

**Comment by Anomareh** [comment]
mynt currently requires Python 2.7, it looks like you're on 3.4.

**Comment by rm2k** [comment]
Yeah, I'm on Python 3.4.3. Any plans to support Python 3.x?

**Comment by Anomareh** [comment]
Sorry for the delay, I've been exceedingly busy. Python 3.x and 2.6 support is on the roadmap, but I'm not sure when it'll make it into the codebase. There were a couple more main features I wanted to implement before porting to other versions.
